#!/usr/bin/env bash

# shellcheck disable=SC2034
LANGUAGE_ARRAY=('ANSIBLE' 'ARM' 'BASH' 'BASH_EXEC' 'CHECKOV' 'CLANG_FORMAT'
  'CLOUDFORMATION' 'CLOJURE' 'COFFEESCRIPT' 'CPP' 'CSHARP'
  'CSS'
  "CSS_PRETTIER"
  'DART'
  'DOCKERFILE_HADOLINT'
  "DOTNET_SLN_FORMAT_ANALYZERS"
  "DOTNET_SLN_FORMAT_STYLE"
  "DOTNET_SLN_FORMAT_WHITESPACE"
  'EDITORCONFIG'
  'ENV'
  'GITHUB_ACTIONS'
  "GITHUB_ACTIONS_ZIZMOR"
  'GITLEAKS'
  "GIT_COMMITLINT"
  "GIT_MERGE_CONFLICT_MARKERS"
  'GO' 'GO_MODULES' 'GO_RELEASER' 'GOOGLE_JAVA_FORMAT'
  "GRAPHQL_PRETTIER"
  'GROOVY'
  'HTML'
  "HTML_PRETTIER"
  'JAVA'
  'JAVASCRIPT_ES' 'JAVASCRIPT_PRETTIER' 'JSCPD' 'JSON'
  "JSON_PRETTIER"
  'JSONC'
  "JSONC_PRETTIER"
  'JSX'
  "JSX_PRETTIER"
  "JUPYTER_NBQA_BLACK"
  "JUPYTER_NBQA_FLAKE8"
  "JUPYTER_NBQA_ISORT"
  "JUPYTER_NBQA_MYPY"
  "JUPYTER_NBQA_PYLINT"
  "JUPYTER_NBQA_RUFF"
  'KOTLIN' 'LATEX' 'LUA' 'MARKDOWN'
  "MARKDOWN_PRETTIER"
  'NATURAL_LANGUAGE' 'OPENAPI' 'PERL' 'PHP_BUILTIN' 'PHP_PHPCS' 'PHP_PHPSTAN'
  'PHP_PSALM' 'POWERSHELL' 'PROTOBUF' 'PYTHON_BLACK' 'PYTHON_PYLINT'
  'PYTHON_FLAKE8' 'PYTHON_ISORT' 'PYTHON_MYPY' 'PYTHON_RUFF'
  'R' 'RENOVATE' 'RUBY' 'RUST_2015'
  'RUST_2018' 'RUST_2021' 'RUST_CLIPPY' 'SCALAFMT' 'SHELL_SHFMT'
  'SNAKEMAKE_LINT' 'SNAKEMAKE_SNAKEFMT' 'STATES' 'SQLFLUFF'
  'TERRAFORM_FMT' 'TERRAFORM_TFLINT' 'TERRAFORM_TERRASCAN' 'TERRAGRUNT'
  "TRIVY"
  'TSX'
  'TYPESCRIPT_ES' 'TYPESCRIPT_PRETTIER'
  'VUE' "VUE_PRETTIER"
  'XML' 'YAML'
  "YAML_PRETTIER"
)
