#!/usr/bin/env bash

declare -l ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT
ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT="${ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT:-"${DEFAULT_ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT}"}"
export ENABLE_GITHUB_PULL_REQUEST_SUMMARY_COMMENT

declare -l SUPPRESS_OUTPUT_ON_SUCCESS
SUPPRESS_OUTPUT_ON_SUCCESS="${SUPPRESS_OUTPUT_ON_SUCCESS:-"false"}"
export SUPPRESS_OUTPUT_ON_SUCCESS
