repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: pretty-format-json
        files: |
          (?x)^(
              test/linters/pre_commit/bad/.*
          )$
