repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: mixed-line-ending
        args:
          - --fix=no
        files: |
          (?x)^(
              test/linters/pre_commit/good/.*
          )$
