---
# https://yamllint.readthedocs.io/en/stable/configuration.html#default-configuration
extends: default

rules:
  line-length:
    max: 120
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
