---
env:
  browser: true
  es6: true
  jest: true
  node: true

extends:
  - "eslint:recommended"

ignorePatterns:
  - "!.*"
  - "**/node_modules/.*"

plugins:
  - n
  - prettier

overrides:
  # JSON files
  - files:
      - "*.json"
    extends:
      - plugin:jsonc/recommended-with-json
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSON

  # JSONC files
  - files:
      - "*.jsonc"
    extends:
      - plugin:jsonc/recommended-with-jsonc
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSONC

  # JSON5 files
  - files:
      - "*.json5"
    extends:
      - plugin:jsonc/recommended-with-json5
    parser: jsonc-eslint-parser
    parserOptions:
      jsonSyntax: JSON5

  # Javascript files
  - files:
      - "**/*.js"
      - "**/*.mjs"
      - "**/*.cjs"
      - "**/*.jsx"
    extends:
      - "plugin:react/recommended"
    parserOptions:
      sourceType: module
      ecmaVersion: latest
      ecmaFeatures:
        jsx: true
        modules: true

  # TypeScript files
  - files:
      - "**/*.ts"
      - "**/*.cts"
      - "**/*.mts"
      - "**/*.tsx"
    extends:
      - "plugin:@typescript-eslint/recommended"
      - plugin:n/recommended
      - plugin:react/recommended
      - prettier
    parser: "@typescript-eslint/parser"
    plugins:
      - "@typescript-eslint"
    parserOptions:
      ecmaVersion: latest
      sourceType: module
