# terrascan configuration file https://github.com/accurics/terrascan/blob/master/config/terrascan.toml

# scan and skip rules configuration
[rules]
    # skip rules (list of rules to skip)
    skip-rules = []
