# Name of the language, in uppercase
language: DOCKERFILE
type: tooling_format

# Define file extensions associated to the language
file_names:
  - "Dockerfile"

# Folder containing test files, if different from language.tolower()
test_folder: docker

linters:

  # dockerfilelint
  dockerfilelint:
    linter_name: dockerfilelint
    name: DOCKERFILE_DOCKERFILELINT
    linter_url: https://github.com/replicatedhq/dockerfilelint
    config_file_name: .dockerfilelintrc
    examples:
      - "dockerfilelint Dockerfile"
      - "dockerfilelint -c .dockerfilelintrc Dockerfile"
    install:
      npm:
        - dockerfilelint

  # Hadolint
  hadolint:
    linter_name: hadolint
    name: DOCKERFILE_HADOLINT
    linter_url: https://github.com/hadolint/hadolint
    linter_image_url: https://hadolint.github.io/hadolint/img/cat_container.png
    config_file_name: .hadolint.yml
    examples:
      - "hadolint Dockerfile"
      - "hadolint -c .dockerfilelintrc Dockerfile"
    install:
      dockerfile:
        - FROM hadolint/hadolint:latest-alpine as dockerfile-lint
        - COPY --from=dockerfile-lint /bin/hadolint /usr/bin/hadolint