# Name of the language, in uppercase
language: DOCKERFILE
type: tooling_format

# Define file extensions associated to the language
file_names:
  - "Dockerfile"

# Folder containing test files, if different from language.tolower()
test_folder: docker

linters:

  # dockerfilelint
  dockerfilelint:
    linter_name: dockerfilelint
    name: DOCKERFILE_DOCKERFILELINT
    linter_url: https://github.com/replicatedhq/dockerfilelint
    config_file_name: .dockerfilelintrc
    examples:
      - "dockerfilelint Dockerfile"
      - "dockerfilelint -c .dockerfilelintrc Dockerfile"

  # Hadolint
  hadolint:
    linter_name: hadolint
    name: DOCKERFILE_HADOLINT
    linter_url: https://github.com/hadolint/hadolint
    linter_image_url: https://camo.githubusercontent.com/ed1547b1b7f6060ad464d180a0c28975ba876830/68747470733a2f2f6861646f6c696e742e6769746875622e696f2f6861646f6c696e742f696d672f6361745f636f6e7461696e65722e706e67
    config_file_name: .hadolint.yml
    examples:
      - "dockerfilelint Dockerfile"
      - "dockerfilelint -c .dockerfilelintrc Dockerfile"