# !/usr/bin/env python3
"""
Unit tests for ANSIBLE linter ansible-lint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class ansible_ansible_lint_test(LinterTestRoot):
    descriptor_id = 'ANSIBLE'
    linter_name = 'ansible-lint'
