# !/usr/bin/env python3
"""
Unit tests for ARM linter arm-ttk
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class arm_arm_ttk_test(TestCase, LinterTestRoot):
    descriptor_id = 'ARM'
    linter_name = 'arm-ttk'
