# !/usr/bin/env python3
"""
Unit tests for BASH linter bash-exec
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class bash_bash_exec_test(LinterTestRoot):
    language = 'BASH'
    linter_name = 'bash-exec'
