# !/usr/bin/env python3
"""
Unit tests for BashShellcheckLinter class
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
import unittest

from superlinter.linters.BashShellcheckLinter import BashShellcheckLinter
from superlinter.tests.test_superlinter.helpers import utilstest


class BashShellcheckLinterTest(unittest.TestCase):
    def setUp(self):
        utilstest.linter_test_setup()

    def test_success(self):
        utilstest.test_linter_success(BashShellcheckLinter(), self)

    def test_failure(self):
        utilstest.test_linter_failure(BashShellcheckLinter(), self)

    def test_get_linter_version(self):
        utilstest.test_get_linter_version(BashShellcheckLinter(), self)
