# !/usr/bin/env python3
"""
Unit tests for C linter cpplint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class c_cpplint_test(LinterTestRoot):
    descriptor_id = 'C'
    linter_name = 'cpplint'
