# !/usr/bin/env python3
"""
Unit tests for CLOJURE linter clj-kondo
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class clojure_clj_kondo_test(LinterTestRoot):
    language = 'CLOJURE'
    linter_name = 'clj-kondo'
