# !/usr/bin/env python3
"""
Unit tests for CLOUDFORMATION linter cfn-lint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class cloudformation_cfn_lint_test(LinterTestRoot):
    language = 'CLOUDFORMATION'
    linter_name = 'cfn-lint'
