# !/usr/bin/env python3
"""
Unit tests for COFFEE linter coffeelint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class coffee_coffeelint_test(TestCase, LinterTestRoot):
    descriptor_id = 'COFFEE'
    linter_name = 'coffeelint'
