# !/usr/bin/env python3
"""
Unit tests for CPP linter cpplint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class cpp_cpplint_test(TestCase, LinterTestRoot):
    descriptor_id = 'CPP'
    linter_name = 'cpplint'
