# !/usr/bin/env python3
"""
Unit tests for CSS linter stylelint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class css_stylelint_test(LinterTestRoot):
    descriptor_id = 'CSS'
    linter_name = 'stylelint'
