# !/usr/bin/env python3
"""
Unit tests for DOCKERFILE linter hadolint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class dockerfile_hadolint_test(LinterTestRoot):
    language = 'DOCKERFILE'
    linter_name = 'hadolint'
