# !/usr/bin/env python3
"""
Unit tests for EDITORCONFIG linter editorconfig-checker
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class editorconfig_editorconfig_checker_test(TestCase, LinterTestRoot):
    descriptor_id = 'EDITORCONFIG'
    linter_name = 'editorconfig-checker'
