# !/usr/bin/env python3
"""
Unit tests for ENV linter dotenv-linter
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class env_dotenv_linter_test(LinterTestRoot):
    descriptor_id = 'ENV'
    linter_name = 'dotenv-linter'
