# !/usr/bin/env python3
"""
Unit tests for GO linter golangci-lint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class go_golangci_lint_test(TestCase, LinterTestRoot):
    descriptor_id = 'GO'
    linter_name = 'golangci-lint'
