# !/usr/bin/env python3
"""
Unit tests for GO linter golangci-lint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class go_golangci_lint_test(LinterTestRoot):
    language = 'GO'
    linter_name = 'golangci-lint'
