# !/usr/bin/env python3
"""
Unit tests for GROOVY linter npm-groovy-lint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class groovy_npm_groovy_lint_test(LinterTestRoot):
    language = 'GROOVY'
    linter_name = 'npm-groovy-lint'
