# !/usr/bin/env python3
"""
Unit tests for HTML linter htmlhint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class html_htmlhint_test(TestCase, LinterTestRoot):
    descriptor_id = 'HTML'
    linter_name = 'htmlhint'
