# !/usr/bin/env python3
"""
Unit tests for JAVA linter checkstyle
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class java_checkstyle_test(LinterTestRoot):
    language = 'JAVA'
    linter_name = 'checkstyle'
