# !/usr/bin/env python3
"""
Unit tests for JAVASCRIPT linter standard
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class javascript_standard_test(LinterTestRoot):
    descriptor_id = 'JAVASCRIPT'
    linter_name = 'standard'
