# !/usr/bin/env python3
"""
Unit tests for JSON linter jsonlint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class json_jsonlint_test(LinterTestRoot):
    language = 'JSON'
    linter_name = 'jsonlint'
