# !/usr/bin/env python3
"""
Unit tests for JSX linter eslint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class jsx_eslint_test(LinterTestRoot):
    descriptor_id = 'JSX'
    linter_name = 'eslint'
