# !/usr/bin/env python3
"""
Unit tests for KOTLIN linter ktlint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class kotlin_ktlint_test(TestCase, LinterTestRoot):
    descriptor_id = 'KOTLIN'
    linter_name = 'ktlint'
