# !/usr/bin/env python3
"""
Unit tests for KOTLIN linter ktlint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class kotlin_ktlint_test(LinterTestRoot):
    descriptor_id = 'KOTLIN'
    linter_name = 'ktlint'
