# !/usr/bin/env python3
"""
Unit tests for KUBERNETES linter kubeval
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class kubernetes_kubeval_test(LinterTestRoot):
    language = 'KUBERNETES'
    linter_name = 'kubeval'
