# !/usr/bin/env python3
"""
Unit tests for KUBERNETES linter kubeval
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class kubernetes_kubeval_test(TestCase, LinterTestRoot):
    descriptor_id = 'KUBERNETES'
    linter_name = 'kubeval'
