# !/usr/bin/env python3
"""
Unit tests for LUA linter luacheck
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class lua_luacheck_test(LinterTestRoot):
    language = 'LUA'
    linter_name = 'luacheck'
