# !/usr/bin/env python3
"""
Unit tests for MARKDOWN linter markdownlint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class markdown_markdownlint_test(LinterTestRoot):
    language = 'MARKDOWN'
    linter_name = 'markdownlint'
