# !/usr/bin/env python3
"""
Unit tests for OPENAPI linter spectral
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class openapi_spectral_test(TestCase, LinterTestRoot):
    descriptor_id = 'OPENAPI'
    linter_name = 'spectral'
