# !/usr/bin/env python3
"""
Unit tests for PERL linter perlcritic
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class perl_perlcritic_test(TestCase, LinterTestRoot):
    descriptor_id = 'PERL'
    linter_name = 'perlcritic'
