# !/usr/bin/env python3
"""
Unit tests for PHP linter psalm
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class php_psalm_test(LinterTestRoot):
    descriptor_id = 'PHP'
    linter_name = 'psalm'
