# !/usr/bin/env python3
"""
Unit tests for PHP linter php
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class php_php_test(LinterTestRoot):
    language = 'PHP'
    linter_name = 'php'
