# !/usr/bin/env python3
"""
Unit tests for PhpPhpStanLinter class
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
import unittest

from superlinter.linters.PhpPhpStanLinter import PhpPhpStanLinter
from superlinter.tests.test_superlinter.helpers import utilstest


class PhpPhpStanLinter_test(unittest.TestCase):
    def setUp(self):
        utilstest.linter_test_setup()

    def test_success(self):
        utilstest.test_linter_success(PhpPhpStanLinter(), self)

    def test_failure(self):
        utilstest.test_linter_failure(PhpPhpStanLinter(), self)

    def test_get_linter_version(self):
        utilstest.test_get_linter_version(PhpPhpStanLinter(), self)
