# !/usr/bin/env python3
"""
Unit tests for POWERSHELL linter powershell
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class powershell_powershell_test(LinterTestRoot):
    language = 'POWERSHELL'
    linter_name = 'powershell'
