# !/usr/bin/env python3
"""
Unit tests for PROTOBUF linter protolint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class protobuf_protolint_test(TestCase, LinterTestRoot):
    descriptor_id = 'PROTOBUF'
    linter_name = 'protolint'
