# !/usr/bin/env python3
"""
Unit tests for PYTHON linter flake8
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class python_flake8_test(TestCase, LinterTestRoot):
    descriptor_id = 'PYTHON'
    linter_name = 'flake8'
