# !/usr/bin/env python3
"""
Unit tests for PYTHON linter pylint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class python_pylint_test(LinterTestRoot):
    descriptor_id = 'PYTHON'
    linter_name = 'pylint'
