# !/usr/bin/env python3
"""
Unit tests for RAKU linter raku
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class raku_raku_test(LinterTestRoot):
    language = 'RAKU'
    linter_name = 'raku'
