# !/usr/bin/env python3
"""
Unit tests for RUBY linter rubocop
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class ruby_rubocop_test(LinterTestRoot):
    descriptor_id = 'RUBY'
    linter_name = 'rubocop'
