# !/usr/bin/env python3
"""
Unit tests for RUBY linter rubocop
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class ruby_rubocop_test(TestCase, LinterTestRoot):
    descriptor_id = 'RUBY'
    linter_name = 'rubocop'
