# !/usr/bin/env python3
"""
Unit tests for SNAKEMAKE linter snakemake
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class snakemake_snakemake_test(LinterTestRoot):
    descriptor_id = 'SNAKEMAKE'
    linter_name = 'snakemake'
