# !/usr/bin/env python3
"""
Unit tests for TERRAFORM linter terrascan
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class terraform_terrascan_test(LinterTestRoot):
    language = 'TERRAFORM'
    linter_name = 'terrascan'
