# !/usr/bin/env python3
"""
Unit tests for TERRAGRUNT linter terragrunt
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class terragrunt_terragrunt_test(LinterTestRoot):
    descriptor_id = 'TERRAGRUNT'
    linter_name = 'terragrunt'
