# !/usr/bin/env python3
"""
Unit tests for TERRAFORM linter terragrunt
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class terraform_terragrunt_test(TestCase, LinterTestRoot):
    descriptor_id = 'TERRAFORM'
    linter_name = 'terragrunt'
