# !/usr/bin/env python3
"""
Unit tests for TERRAFORM linter tflint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class terraform_tflint_test(LinterTestRoot):
    descriptor_id = 'TERRAFORM'
    linter_name = 'tflint'
