# !/usr/bin/env python3
"""
Unit tests for TSX linter eslint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class tsx_eslint_test(TestCase, LinterTestRoot):
    descriptor_id = 'TSX'
    linter_name = 'eslint'
