# !/usr/bin/env python3
"""
Unit tests for TSX linter eslint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class tsx_eslint_test(LinterTestRoot):
    language = 'TSX'
    linter_name = 'eslint'
