# !/usr/bin/env python3
"""
Unit tests for TYPESCRIPT linter eslint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class typescript_eslint_test(TestCase, LinterTestRoot):
    descriptor_id = 'TYPESCRIPT'
    linter_name = 'eslint'
