# !/usr/bin/env python3
"""
Unit tests for TYPESCRIPT linter standard
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class typescript_standard_test(LinterTestRoot):
    descriptor_id = 'TYPESCRIPT'
    linter_name = 'standard'
