# !/usr/bin/env python3
"""
Unit tests for XML linter xmllint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class xml_xmllint_test(LinterTestRoot):
    language = 'XML'
    linter_name = 'xmllint'
