# !/usr/bin/env python3
"""
Unit tests for YAML linter yamllint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""

from unittest import TestCase

from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class yaml_yamllint_test(TestCase, LinterTestRoot):
    descriptor_id = 'YAML'
    linter_name = 'yamllint'
