# !/usr/bin/env python3
"""
Unit tests for YAML linter yamllint
This class has been automatically generated by .automation/build.py, please do not update it manually
"""
from superlinter.tests.test_superlinter.LinterTestRoot import LinterTestRoot


class yaml_yamllint_test(LinterTestRoot):
    language = 'YAML'
    linter_name = 'yamllint'
